import type { Metadata } from "next";
import "./globals.css";

import LayoutBody from "@/components/LayoutBody";

export const metadata: Metadata = {
  title: "FilmScope",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LayoutBody>{children}</LayoutBody>
    </html>
  );
}
